b1 = Brand.create(name:"Maybelline")
b2 = Brand.create(name:"Revlon")
b3 = Brand.create(name:"Chanel")
b4 = Brand.create(name:"Loreal")
b5 = Brand.create(name:"NARS")

p1 = Product.create(name: "foundation", description: "nice", price: 40, brand_id: 2)
p2 = Product.create(name: "lipstick", description: "cool", price: 20, brand_id: 1)
p3 = Product.create(name: "blush", description: "pretty", price: 20, brand_id: 1)
p4 = Product.create(name: "mascara", description: "red", price: 20, brand_id: 1)
p5 = Product.create(name: "eyeliner", description: "blue", price: 20, brand_id: 1)

r1 = Review.create(content: "love it", user: u1 , product_id: 1)
r2 = Review.create(content: "like it", user: u2 , product_id: 2)
r3 = Review.create(content: "gotta have it", user: u3 , product_id: 3)
r4 = Review.create(content: "want it", user: u4 , product_id: 4)
r5 = Review.create(content: "really want it it", user: u5 , product_id: 5)

u1 = User.create(name: "Ava")
u2 = User.create(name: "Bob")
u3 = User.create(name: "Carrie")
u4 = User.create(name: "Daniel")
u5 = User.create(name: "Ethan")
